/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package pl.edu.pw.iem.modrzejm.amath;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int etExpression=0x7f050001;
        public static final int lvValues=0x7f050000;
        public static final int teRowTextExpression=0x7f050004;
        public static final int teRowTextValue=0x7f050005;
        public static final int tvRowNumber=0x7f050003;
        public static final int tvSession=0x7f050002;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int values_row=0x7f030001;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int body=0x7f040003;
        public static final int confirm=0x7f040004;
        public static final int hello=0x7f040000;
        public static final int title=0x7f040002;
    }
}
